force-app/main/default/objects/Account2__c/Account2__c.object-meta.xml
<CustomObject>
    <label>Account2</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account2</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact2__c/Contact2__c.object-meta.xml
<CustomObject>
    <label>Contact2</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact2__c/fields/Account2__c.field-meta.xml
<CustomField>
    <fullName>Account2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account2</label>
    <referenceTo>Account2__c</referenceTo>
    <relationshipLabel>Contact2</relationshipLabel>
    <relationshipName>Contact2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact2__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>In Active</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Account2Ext.cls
public class Account2Ext {

 public Account2__c acct{get; set;}
    
    
    public PageReference save() {
      Savepoint sp = Database.setSavepoint();
      System.debug('test message2');
      try{
        
        Insert acct;
        System.debug('Account Created: '+acct.id);
        System.debug('Account Created: '+acct.id);
        Contact2__c con= new Contact2__c();
        con.name='Test Contact';
        con.status__c='Active';
        con.StartDate__c=Date.today().addDays(-2);
        con.Account2__c=acct.id;
        insert con;
        PageReference acctPage = new ApexPages.StandardController(acct).view();
        acctPage.setRedirect(true);
        return acctPage;
        }
        
        catch(DMLException e){
        Database.rollback(sp);
        ApexPages.Message msg=new ApexPages.Message(ApexPages.Severity.error,e.getDmlMessage(0) );
ApexPages.addMessage(msg);
        return null;
        }
        
    }

   
    
    public Account2Ext (){
    if(acct==null){ acct=new Account2__c();}
        System.debug('Record: '+acct);
       String id= ApexPages.currentPage().getParameters().get('id');
       If(id!=null){
       //acct=[SELECT name,   tekmind__StartDate__c FROM TestObject__c WHERE id=:id limit 1];
       
       }
    }

    public String getGreeting() {
       // return 'Hello ' + acct.name + ' (' + acct.id + ')';
       return 'hello';
    }
}